[[mgr.prepend_keymap]]
    on   = [ "<C-s>" ]
    run  = 'shell "$SHELL" --block --confirm'
    desc = "Open shell here"
[[mgr.prepend_keymap]]
    on   = [ "g", "b" ]
    run  = 'shell "bat $0" --block --confirm'
    desc = "View with bat"
[[mgr.prepend_keymap]]
    on   = "l"
    run  = "plugin smart-enter"
    desc = "Enter the child directory, or open the file"
[[mgr.prepend_keymap]]
    on   = [ "g", "s" ]
    run  = 'shell "lazygit" --block --confirm'
    desc = "Open lazygit"
[[mgr.prepend_keymap]]
    desc = "Start bunny.yazi"
    on = ";"
    run = "plugin bunny"
