tap "homebrew/bundle"

# required for zsh-fzf-completion
brew "gawk"
brew "grep"
brew "gnu-sed"
brew "coreutils"

#Tools
brew "fd"
brew "jq"
brew "ripgrep"
brew "unar"
brew "wget"

# Terminal
brew "bat"
brew "eza"
brew "fzf"
brew "yazi"
brew "zellij"
brew "zoxide"
brew "starship"
brew "diff-so-fancy"
brew "starship"
brew "zoxide"

# Neovim
brew "lua"
brew "luajit"
brew "neovim"

# Dev
brew "lazygit"
brew "chezmoi"
